steps:
  # 1. Build Docker
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args: [ 'build', '-t', 'europe-docker.pkg.dev/$PROJECT_ID/bitten-back-images/bitten-api:$COMMIT_SHA', '.' ]

  # 2. Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: [ 'push', 'europe-docker.pkg.dev/$PROJECT_ID/bitten-back-images/bitten-api:$COMMIT_SHA' ]

  # 3. Deploy in Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bitten-api-service'
      - '--region=europe-west1'
      - '--image=europe-docker.pkg.dev/$PROJECT_ID/bitten-back-images/bitten-api:$COMMIT_SHA'
      - '--platform=managed'
      - '--ingress=internal-and-cloud-load-balancing'
      - '--service-account=cloud-build-deployer@$PROJECT_ID.iam.gserviceaccount.com'
      - '--update-secrets=DB_PASSWORD=DB_PASSWORD:latest,DB_USER=DB_USER:latest'
      - '--add-cloudsql-instances=$PROJECT_ID:europe-west1:bitten-db-ew1'
      - '--set-env-vars=INSTANCE_CONNECTION_NAME=$PROJECT_ID:europe-west1:bitten-db-ew1'


options:
  logging: CLOUD_LOGGING_ONLY