steps:
  # 1. Build Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-north1-docker.pkg.dev/$PROJECT_ID/bitten-back-images/bitten-api:$COMMIT_SHA', '.']

  # 2. Download in Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-north1-docker.pkg.dev/$PROJECT_ID/bitten-back-images/bitten-api:$COMMIT_SHA']

  # 3. Deploy in Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bitten-api-service'
      - '--region=europe-north1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=cloud-build-deployer@$PROJECT_ID.iam.gserviceaccount.com'
      - '--update-secrets=DB_PASSWORD=DB_PASSWORD:latest,DB_USER=DB_USER:latest'

      - '--add-cloudsql-instances=$PROJECT_ID:europe-north1:cloudsql'


images:
  - 'europe-north1-docker.pkg.dev/$PROJECT_ID/bitten-back-images/bitten-api:$COMMIT_SHA'