services:
  postgres:
    image: postgres:17.5
    container_name: local_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: truapp00 # I WILL REPLACE THIS SHIT
      POSTGRES_DB: bitcloud
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists database data.
    ports:
      - "5432:5432" # Maps container port 5432 to host port 5432.
    networks:
      - appnet
    restart: unless-stopped

  app:
    build:
      context: . # Specifies the build context path (location of Dockerfile).
      dockerfile: Dockerfile # Specifies the Dockerfile name.
    container_name: bitten_api
    depends_on:
      - postgres # Ensures PostgreSQL starts before the application.
    ports:
      - "9080:9080" # Maps container port 9080 to host port 9080.
    environment:
      LOG_LEVEL: debug
      DB_HOST: postgres # Service name of the PostgreSQL container.
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: truapp00 # I WILL REPLACE THIS SHIT
      DB_NAME: bitcloud
      DB_SSLMODE: disable # SSL mode for database connection.
      DB_MAX_OPEN_CONNS: 25
      DB_MAX_IDLE_CONNS: 25
      DB_CONN_MAX_LIFETIME_MINUTES: 5
      DB_GORM_LOG_LEVEL: info # Log level for GORM ORM.
      DB_GORM_SLOW_THRESHOLD_MS: 500 # Threshold for GORM to log slow queries (in milliseconds).

      API_HOST: "0.0.0.0" # Application API will listen on all network interfaces within the container.
      API_PORT: 9080
      API_READ_TIMEOUT_SECONDS: 10
      API_WRITE_TIMEOUT_SECONDS: 10
      API_IDLE_TIMEOUT_SECONDS: 120
      API_READ_HEADER_TIMEOUT_SECONDS: 5
      API_SHUTDOWN_TIMEOUT_SECONDS: 20

    networks:
      - appnet
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: local_nginx
    ports:
      - "80:80" # Maps container port 80 to host port 80.
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mounts the local nginx.conf file as read-only into the container.
    depends_on:
      - app # Ensures the application starts before Nginx.
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet: # Defines a custom bridge network for inter-service communication.
    driver: bridge

volumes:
  postgres_data: # Defines a named volume to persist PostgreSQL data.